dotkom/monoweb

- src/components/atoms/button/button.stories.tsx
- src/styles/colors.ts
- src/styles/components/button.ts
I've added the colors gray, blue, green, red and orange.
Blue will be used as the brand and info color
Green will be used for success
Red will be used for errors
Orange will be used as a secondary color, and also as a warning color
> feat(colors): add first draft of color theme

- apps/ow-api/package.json
- apps/ow-api/src/context.ts
- apps/ow-api/src/modules/auth/__test__/user-service.spec.ts
- apps/ow-api/src/modules/auth/user-service.ts
- apps/ow-api/src/modules/auth/user.ts
- apps/ow-api/src/modules/company/company.ts
- apps/ow-api/src/modules/event/__test__/event-service.spec.ts
- apps/ow-api/src/modules/event/event.ts
- apps/ow-api/src/server.ts
- packages/ow-db/src/index.ts
- turbo.json
- yarn.lock
- export a global default Prisma
- instead of using models, we use the type `Prisma.___GetPayload<null>`. That way we can avoid conflicts between the typing of prisma and the normal types
- owdb is copied from cal.com
> Fix type errors from backend and prisma

- apps/db-migrator/src/db.ts
- apps/db-migrator/src/index.ts
- apps/db-migrator/src/seed.ts
- packages/api/src/modules/auth/user-repository.ts
- packages/api/src/modules/company/company-repository.ts
- packages/api/src/modules/event/event-repository.ts
- packages/ow-db/src/index.ts
- packages/ow-db/src/migrations/0001_create_user_and_auth.ts
- packages/ow-db/src/migrations/0002_create_company.ts
- packages/ow-db/src/migrations/0003_create-event.ts
- packages/ow-db/src/migrator.ts
- packages/ow-db/src/types/index.ts
- Converts table names to snake case
- This is due to capitlized letters not working correctly with the camelcase plugin, which is prefered in javascript
> Convert PascalCase to snake_case for table names

- packages/ow-db/src/cockroach.ts
- packages/ow-db/src/index.ts
- packages/ow-db/src/migrator.ts
Addresses a problem where the migrator wouldn't run because the adapter wasn't exported, while still making it possible for nextjs to run without having to resolve the new URL in createMigrator
> fix: re-export cockroach dialect and adapter separately from migrator

- .vscode/settings.json
- apps/db-migrator/package.json
- apps/db-migrator/src/fixture.ts
- apps/db-migrator/src/fixtures/attendance.ts
- apps/db-migrator/src/fixtures/attendee.ts
- apps/db-migrator/src/fixtures/committee.ts
- apps/db-migrator/src/fixtures/company.ts
- apps/db-migrator/src/fixtures/event-company.ts
- apps/db-migrator/src/fixtures/event.ts
- apps/db-migrator/src/fixtures/mark.ts
- apps/db-migrator/src/fixtures/user.ts
- apps/db-migrator/src/index.ts
- package.json
- pnpm-lock.yaml
- Adds three new commands
- `pnpm migrate-down` - Migrates down to the previous migration
- `pnpm migrate-down-all` - Migrates down all migrations in the correct order
- `pnpm migrate-with-fixtures` - Migrates to the latest migration and inserts predictable fixture data
> Add db fixtures and additional migrate options

- apps/db-migrator/src/fixture.ts
- apps/db-migrator/src/fixtures/committee.ts
- apps/db-migrator/src/fixtures/event.ts
- apps/sanity/package.json
- apps/web/src/components/layout/EntryDetailLayout.tsx
- apps/web/src/components/views/CommitteeView/index.tsx
- apps/web/src/pages/committee/[id].tsx
- apps/web/src/pages/committee/index.tsx
- packages/api/src/modules/event/event-repository.ts
- packages/api/src/modules/event/event-router.ts
- packages/api/src/modules/event/event-service.ts
- packages/config/tailwind-preset.js
- packages/ow-db/src/migrations/0011_alter_committee.ts
- packages/ow-db/src/types/committee.ts
- packages/types/src/committee.ts
- pnpm-lock.yaml
- Adds a page to display info about a committee. Uses the same layout as the company page
- Extends the committee table with additional fields such as `description`, `email` and `image`
1. Run migrations (I recommend `pnpm migrate-with-fixtures` for the latest fixture data)
2. Spin monoweb up and go to `/committee`
> Add committee page

- apps/dashboard/src/app/user/page.tsx
Users table was copy pasted without changing the title, this fixes it.
> Fixed users table title

- .github/workflows/tflint.yml
- infra/README.md
- infra/vercel/.terraform.lock.hcl
- infra/vercel/dns.tf
- infra/vercel/main.tf
- infra/vercel/providers.tf
- infra/vercel/terraform.tf
Adds terraform configuration and mini setup guide on how we use workspaces.
The branch is currently applied onto the `dev` workspace which means https://dev.monoweb.online.ntnu.no/ is publicly reachable.
> Import vercel project into terraform configuration

- infra/neon/.terraform.lock.hcl
- infra/neon/terraform.tf
Should prevent any bad actors from messing with the original package, also means we manage our own release cycle for the neon provider
- https://registry.terraform.io/providers/dotkom/neon/latest
- https://github.com/dotkom/terraform-provider-neon
> Use self-released version of neon provider

- apps/dashboard/next.config.mjs
- apps/web/next.config.mjs
this removes an unneeded option which was experimental and now is default
Gets rid of this junk:
> remove appDir option

- apps/dashboard/src/app/ApplicationShell.tsx
Stores the opened labels in local storage and reopens them on page load so that their state persists
> keep expanded navbar labels when navigating dashboard

- packages/auth/src/auth-options.ts
Our cognito schema doesn't define this anymore so it's always undefined
> Remove middlename claim

- apps/web/src/components/layout/ProfileLayout.tsx
- apps/web/src/components/organisms/Navbar/components/profile/ProfileMenu/ProfileMenuContainer.tsx
- apps/web/src/components/views/ProfileView/components/ProfileLanding.tsx
- apps/web/src/pages/profile/email.tsx
- apps/web/src/pages/profile/index.tsx
- apps/web/src/pages/profile/membership.tsx
- apps/web/src/pages/profile/password.tsx
- apps/web/src/pages/profile/penalties.tsx
- apps/web/src/pages/profile/privacy.tsx
- apps/web/src/utils/penalty-rules.tsx
- packages/ui/src/index.ts
Closes: #..
- Created penalty page without functionality
- Updated to automatically show titles in profile pages
- Removed hardcoded title/header from pages in profile (Not notifications, accesscard and payments because they will be removed in another branch by @hanlun0804 )
- Exported Accordion from storybook
- Run monoweb
- Navigate to <code>/profile</code> in URL
> Create penalty page

- apps/dashboard/package.json
- apps/dashboard/stubs/pg-native/package.json
- apps/dashboard/stubs/pg-native/pgnative.stub.cjs
Next.js tries to include pg-native which is a module that uses C++ addons into the webpack build on the server (because we have transpilePackages)
It errors because it thinks the package will end up on the client, but it won't so for webpack we will just stub it
> Add stub for pg-native for dashboard

- apps/rif/src/app/checkbox.tsx
Fixes the problem where the tooltip triggers acted as submit buttons triggering both accidental submit and accidental validation
> Prevent tooltip buttons from submitting the form

- apps/web/src/components/views/CareerView.tsx
Closes: #...
- Removed z-index property for div in CareerView
- Run monoweb
- Navigate to <code>localhost:3000/career</code>
- Hover over "Om oss" and "For bedrifter"
> Fix career page navbar bug

- apps/dashboard/src/modules/committee/queries/use-committee-all-query.ts
- apps/web/src/pages/committee/[id].tsx
- packages/core/src/modules/committee/committee-repository.ts
- packages/core/src/modules/committee/committee-service.ts
- packages/core/src/utils/db-utils.ts
- packages/gateway-trpc/src/modules/committee/committee-router.ts
Problems this solves outlined in https://linear.app/dotkom/issue/DOT-426/make-all-backend-endpoints-return-a-collection-type
All the client queries now have a cursor argument they can use to determine if there is more data coming
The end goal is to replace every orderedQuery with paginatedQuery
> Create paginated collection builder

- apps/web/src/pages/committee/index.tsx
#711  One usage of the committee router was not updated to the new return type. This is currently breaking the deployment of main.
> fix: code not updated to collections system

- infra/core/main.tf
> Register AWS Route53 zone for vinstraff.no

- infra/auth0/main.tf
https://github.com/auth0/node-auth0
> Management API Client
The Auth0 Management API is meant to be used by back-end servers or trusted parties performing administrative tasks. Generally speaking, anything that can be done through the Auth0 dashboard (and more) can also be done through this API.
> 
> Initialize your client class with a client ID, client secret and a domain.
> 
> import { ManagementClient } from 'auth0';
> 
> var management = new ManagementClient({
domain: '{YOUR_TENANT_AND REGION}.auth0.com',
clientId: '{YOUR_CLIENT_ID}',
clientSecret: '{YOUR_CLIENT_SECRET}',
});
We need the backend to be able to talk to the management api. One use case is for implementing user search in the dashbaord for event attendance. This PR creates an auth0 machine to machine application (client) …
> add auth0 client for making management api calls from sdk in backend

- apps/dashboard/src/modules/event/mutations/use-register-for-event-mutation.ts
- apps/dashboard/src/modules/event/mutations/use-update-event-attendance-mutation.ts
- infra/auth0/main.tf
- packages/core/src/modules/core.ts
- packages/core/src/modules/event/event-committee-service.ts
- packages/core/src/modules/mark/personal-mark-repository.ts
- packages/core/src/modules/mark/personal-mark-service.ts
- packages/core/src/modules/user/user-service.ts
- packages/gateway-trpc/src/modules/mark/personal-mark-router.ts
Core should only expose the contracts of repositories/services and not the individual implementations. This way we force the contracts to stay updated as well, as previously you could add new methods to a service and get access to it thorugh core without updating interface.
Includes fix for EventCommitteeServiceImpl which was not following the EventCommitteeService interface.
All this PR does is adding the interface types to all repositories/services in core and fixes some issues that arose from this
> Make core expose contract apis, not direct implementation apis

- packages/db/src/db.generated.d.ts
- tools/migrator/src/fixture.ts
- tools/migrator/src/fixtures/attendance.ts
- tools/migrator/src/fixtures/attendee.ts
- tools/migrator/src/fixtures/committee-organizer.ts
- tools/migrator/src/fixtures/committee.ts
- tools/migrator/src/fixtures/company.ts
- tools/migrator/src/fixtures/event-company.ts
- tools/migrator/src/fixtures/event.ts
- tools/migrator/src/fixtures/job-listing.ts
- tools/migrator/src/fixtures/mark.ts
- tools/migrator/src/fixtures/offline.ts
- tools/migrator/src/fixtures/personal-mark.ts
- tools/migrator/src/fixtures/product-payment-provider.ts
- tools/migrator/src/fixtures/product.ts
- tools/migrator/src/fixtures/user.ts
**Background**
I was creating new fixtures due to some changes that needed to be made to the database schema. I found it very annoying to generate the ulids manually, seeing that the ulids should be absolutely ordered based on insert time. Ended up rewriting such that the ids are generated by the database. 
**Changes**
- Use functions to generate fixtures instead of hard-coded objects so that you can inject FK-IDs from previous fixtures
- some helper functions to make the code a bit neater
> Refactor fixture generation

- packages/core/src/modules/job-listing/__test__/job-listing.e2e-spec.ts
- packages/core/src/modules/user/__test__/user-service.e2e-spec.ts
- packages/core/vitest-integration.setup.ts
**Note: this is a PR against the branch of #829 **
Removes the need to elide dbName into variable, making it less error prone. Also does sharing of Kysely instances
> Clean up and reduce boilerplate in test setup

- packages/core/package.json
- packages/core/src/modules/job-listing/__test__/job-listing.e2e-spec.ts
- packages/core/src/modules/user/__test__/user-service.e2e-spec.ts
- packages/core/vitest-integration.config.ts
- packages/core/vitest-integration.setup.ts
- pnpm-lock.yaml
Set up _one_ container at the start of running tests. Instead of starting new containers for each test, do this:
```
beforeEach(async () => {
const env = createEnvironment()
await runMigrations(env)
})
afterEach(async () => {
const env = createEnvironment()
await resetTestDatabase(container, env)
})
```
**Note**:
I added the `withReuse()` option to the `PostgreSqlContainer`. I __think__ this should run fine in ci but I'm not 100% sure.
**Before:**
```
✓ src/modules/user/__test__/user-service.e2e-spec.ts (4) 35020ms
✓ users (4) 35020ms
✓ can create new users 9889ms
✓ will not allow two users the same subject 8424ms
✓ will find users by their user id 8364ms
✓ can update users given their id 8342ms
```
**After:**
Without reusing container
```
✓ …
```
> Improve performance in integration tests

- packages/db/src/db.generated.d.ts
- packages/db/src/migrations/0026_no_null_event_types.js
This fixes a bug where you are allowed to insert events with event type null into the database, which then crashes when trying to retrieve them.
> Make event types not nullable

- apps/dashboard/src/utils/trpc.ts
I have found it pretty confusing to debug issues where the root issue has been that the trpc server has not been responding. I.e. if you forget to run `web` now that it is hosted through that app. Maybe this helps someone that goes into the same trap of not running the trpc server.
Without this, all you get is "TypeError: failed to fetch". But for someone that's not a pro in trpc and how it works, it can be pretty confusing
> Add helpful log if the fetch call to the trpc server fails

- apps/dashboard/src/app/QueryProvider.tsx
I think having request retries and window refetching makes little sense during development.
> Turn off retry and refetch on window focus during development

- packages/core/src/modules/external/auth0-synchronization-service.ts
- packages/logger/package.json
- packages/logger/src/index.ts
- pnpm-lock.yaml
- tools/migrator/src/index.ts
Previously it was not possible to log out objects using the winston logger. This adds support for this using interpolation in the message. It also adds some padding to the `info` part such that messages start from the same column.
Example console output
```ts
const logger = getLogger("service a")
logger.error("error message")
logger.warn("warn message")
logger.info("info message")
logger.http("http message")
logger.verbose("verbose message")
logger.debug("debug message")
logger.silly("silly message")
console.log("")
logger.info("test info message from service a")
logger.info("message with metadata2 %o", { message: "John Doe", id: 123 })
const error = new Error("Something failed!")
logger.error("hello world %O", error)
```
New
Old (set to only showing info and more serious):
> Improve logging package config

- apps/invoicification/src/app/page.tsx
Bekk representative was complaining that when you click submit on the form seemingly all the form values disappear, making it seem like an empty form was submitted. This PR removes the form reset on submit. Since we redirect on success anyways, it is not necessary to reset the form when successfull, and if the submit fails it is also IMO better to keep the values.
> Don't reset invoicification form when submitting

- infra/auth0/branding/universal_login_base.html
This PR changes the background of our Auth0 logins
This is how it is currently:
> Update login background

- packages/db/src/migrations/0029_add_user_attributes.js
Down migrations weren't working due to a non-nullable field being renamed by recreating it.
> Fix down migrations

- apps/dashboard/src/modules/job-listing/modals/create-job-listing-modal.tsx
- packages/types/src/job-listing.ts
Tok alt for lang tid å finne buggen haha
Fixing where the job listing wont be published since it asks for createdAt date.
Reason for switching to .partial() is so that we can get the zod error messages. It keeps the same flow with not publishing if fields is not filled
> fix: Publish job listing

- infra/auth0/main.tf
- Fixed `/docs` redirect uri for production environment
- Added localhost to staging environment redirect uris
> Fix incorrect redirect uris for vengeful vineyard

- .github/workflows/ci.yml
Disabled because they lack environment variables, and we don't have a good way to sync doppler to GitHub without risk of duplication in environment variable names.
Besides, these get built and pre-viewed on Vercel anyways, so I don't believe we're losing anything important.
> Disable building web and dashboard in CI

- infra/auth0/main.tf
This enables the login with Feide option in auth0 (for ow4 and monoweb)
> Enable Feide login in auth0

- infra/auth0/appkom.tf
- infra/auth0/js/actions/linkFeideAccounts.js
- infra/auth0/js/fetchUserProfile.js
- infra/auth0/main.tf
This PR automatically connects new Feide accounts to existing Onlineweb accounts. 
This is implemented by:
* Adding the NTNU-username to the info gathered by the Feide fetchUserProfile, and placing it in the app_metadata (and switching it from using request to async fetch to avoid excessive nesting)
* Creating a Machine-to-machine application in auth0 to access the management API
* Adding a post login action which uses the management api to look for accounts with a matching `ntnu_username` in the app metadata, and then links them
> Add automatic Feide account linking

- packages/db/package.json
- packages/db/src/index.ts
- pnpm-lock.yaml
Makes it easier to identify if no certificate authority is provided.
Also gives a warning to local users that the config is only valid for local.
> Emit warning if no certificate authority is provided

- .github/CODEOWNERS
This introduces (and suggests some codeowners to begin with) that we use GitHub codeowners feature for auto-assigning reviewers to pull requests.
Historically speaking we haven't been the best at reviewing eachother's patches, so having GitHub autoassign *somebody* means contributors don't need to consider who to ask, and it's easier for people who wrote the code to see and follow updates.
I don't intend to take the name "codeowners" very seriously. It's just so GitHub can auto-assign reviewers.
This list is incomplete now, but I've proposed some initial codeowners for code I know people have worked a lot on. This also doesn't prevent others from chiming in on PRs, but it should hopefully help us forget about PRs.
> Propose introducing codeowners for GitHub reviewer assignent

- apps/dashboard/src/env.ts
- apps/dashboard/src/trpc.ts
- apps/web/src/env.ts
- apps/web/src/utils/trpc/client.ts
- packages/environment/src/index.mjs
Reverts two prior commits and passes the arguments as parameters to createEnvironment as intended.
This keeps the type safety that we intended for the environment package
cc @jotjern
> Do not directly access client variables without createEnvironment

- infra/auth0/main.tf
- We need to read users to check if an users has a ntnu_username already
---
name: ''
about: ''
title: ''
labels: ''
assignees: ''
---
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Add permissions to ow4 mgmt-client

- docker-compose.yml
> Remove version field in docker compose

- apps/web/package.json
- pnpm-lock.yaml
We use iconify or radix icons everywhere (arguably radix-icons should also go)
> Remove unused react-icons package

- .github/workflows/ci.yml
- apps/brevduen/Dockerfile
- package.json
We are using --experimental-strip-types for rpc, and the nvmrc has been
at 22 for a long time. 22 is also the active version right now
> Set minimum node version to 22

- .github/renovate.json
We do this at work and I think it's pretty nice. Helps keep the maintenance burden down. And we have a low risk application, so I think it's worth the occasional problematic merge
The matchCurrentVersion setting above is a rule to exclude any dependencies which are pre-1.0.0 because those can make breaking changes at any time according to the SemVer spec.
> Enable automerge for patch and minor

- apps/rpc/Dockerfile
Previously I used this to have prisma auto generate, but its safer to just run it manually
> Disable postinstall scripts in Dockerfile

- README.md
We are not sponsored by them so there is no contractual obligation to
have their logo mark anywhere
> Remove Vercel logo from README

- .github/workflows/ci.yml
- apps/dashboard/Dockerfile
- apps/dashboard/src/env.ts
- apps/web/Dockerfile
- apps/web/src/env.ts
- packages/auth/package.json
- packages/auth/src/auth-options.ts
- packages/environment/src/index.mjs
- pnpm-lock.yaml
- turbo.json
`token.sub` gives you the provider sub. If the user logs in via FEIDE,
this field becomes the FEIDE sub - not the Auth0 one. This change uses
the access token to derive the Auth0 sub.
> Use subject claim from access token in sign-in

- apps/dashboard/src/env.ts
- apps/web/src/env.ts
When deployed behind ALB we need this variable, otherwise authjs thinks
we are going back to localhost:3000
> Add optional AUTH_URL variable

- apps/dashboard/src/app/(dashboard)/company/write-form.tsx
- apps/dashboard/src/app/(dashboard)/group/write-form.tsx
- apps/dashboard/src/app/(dashboard)/interest-group/write-form.tsx
This PR updates the image input fields in the write forms for companies, groups, and interest groups. Instead of using text inputs where users would need to provide image URLs, we now use file inputs that allow direct file uploads.
Changes include:
- Importing `createFileInput` in all three form files
- Replacing `createTextInput` with `createFileInput` for image fields
- Updating labels and adding appropriate placeholders for the upload fields
This change improves the user experience by allowing direct file uploads rather than requiring users to provide image URLs manually.
> Replace text inputs with file inputs for image uploads

- packages/config/tailwind-preset.js
The default for brand color in the tailwind preset was brand-3, whereas the actual brand color for Online (#0D5474) was brand-9
> Fix bug where brand color default was brand-3

- .github/workflows/deploy-prod.yml
Updated CloudFront distribution ID in the production deployment workflow from E60JFQ13PM11R to E3J930LEDCHBY3. This change ensures cache invalidation operations target the correct distribution during deployments.
> Update CloudFront distribution ID in production deployment workflow

- apps/kvittering-frontend/src/components/receipt-form.tsx
Increased the maximum number of files allowed in the receipt form dropzone from 5 to 20, while maintaining the same file size limit of 50MB per file.
> Increase maximum file upload limit from 5 to 20

- apps/kvittering-frontend/src/components/ui/file-upload.tsx
> Decrease to max 1MB attachments compressed

- apps/kvittering-frontend/src/components/receipt-form.tsx
- apps/kvittering-frontend/src/components/ui/file-upload.tsx
- apps/kvittering-frontend/src/lib/alert.ts
This PR adds Slack notifications for important events in the receipt form submission process. A new `alertFormSubmission` function sends messages to a `tmp-kvittering-submissions` Slack webhook when:
1. A user submits the receipt form (including their name and number of attachments)
2. PDF generation fails
3. Email sending fails
4. PDF to image conversion fails
5. Image compression fails
6. File upload fails
These notifications will help track form submissions and quickly identify when users encounter errors during the process.
> Setup alerting about errors in frontend until stuff has stabilized

- apps/kvittering-frontend/src/lib/alert.ts
- apps/kvittering-frontend/src/main.tsx
Moved hardcoded API keys to environment variables for improved security
This PR replaces hardcoded API keys with environment variables:
- Replaced the Slack webhook URL with `import.meta.env.VITE_SLACK_ALERT_WEBHOOK_URL`
- Replaced the Sentry DSN with `import.meta.env.VITE_SENTRY_DSN`
These changes enhance security by removing sensitive credentials from the codebase and make the application more configurable across different environments.
> Move sentry dsn and slack webhook url to environment variables

- apps/brevduen/Dockerfile
- apps/dashboard/Dockerfile
- apps/invoicification/Dockerfile
- apps/rif/Dockerfile
- apps/rpc/Dockerfile
- apps/web/Dockerfile
Fixes MONO-369
The JSON-prune tree from `turbo prune` causes the lockfile to point to
files that don't exist, rendering the entire lockfile broken and pnpm
having to build a fresh lock. This means the pnpm-lock.yaml we have in
root is not used at all, and this can lead to build differences.
When building with the full pruned tree this no longer happens.
> Copy full turbo prune tree in Docker builds

- apps/kvittering-backend/src/server.py
Added the user's email to the CC list when sending emails. This ensures that the person submitting the form receives a copy of the email, improving transparency and providing confirmation that their submission was processed.
> Add submitter's email to CC recipients in email sending

- package.json
Added a new script `dev:core-web` to run a subset of packages in development mode. This script runs the UI, web, dashboard, and RPC packages in parallel with Doppler environment variables, excluding the invoicification and rif packages that are included in the full `dev` script.
> Add dev:core-web script for running core web services

- apps/rpc/src/env.ts
- apps/rpc/src/index.ts
- packages/gateway-trpc/src/context.ts
- packages/gateway-trpc/src/modules/article/article-router.ts
- packages/gateway-trpc/src/modules/company/company-router.ts
- packages/gateway-trpc/src/modules/event/attendance-router.ts
- packages/gateway-trpc/src/modules/event/event-router.ts
- packages/gateway-trpc/src/modules/group/group-router.ts
- packages/gateway-trpc/src/modules/interest-group/interest-group-router.ts
- packages/gateway-trpc/src/modules/job-listing/job-listing-router.ts
- packages/gateway-trpc/src/modules/mark/mark-router.ts
- packages/gateway-trpc/src/modules/mark/personal-mark-router.ts
- packages/gateway-trpc/src/modules/offline/offline-router.ts
- packages/gateway-trpc/src/modules/payment/payment-router.ts
- packages/gateway-trpc/src/modules/payment/product-router.ts
- packages/gateway-trpc/src/modules/payment/refund-request-router.ts
- packages/gateway-trpc/src/modules/user/user-router.ts
- packages/gateway-trpc/src/trpc.ts
This PR adds proper admin authorization to the API by implementing an admin-specific procedure that checks if the authenticated user is in the list of admin users. The changes include:
1. Added an `ADMIN_USERS` environment variable that contains a comma-separated list of Auth0 user IDs with admin privileges
2. Created a new `adminProcedure` middleware that verifies if the authenticated user is in the admin list
3. Updated all administrative endpoints to use the new `adminProcedure` instead of `protectedProcedure` or `publicProcedure`
4. Passed the list of admin principals through the context to make it available for authorization checks
This change ensures that only designated admin users can access sensitive endpoints for creating, updating, and deleting resources, while regular …
> Add admin authorization to API endpoints

- packages/gateway-trpc/src/modules/company/company-router.ts
- packages/gateway-trpc/src/modules/group/group-router.ts
- packages/gateway-trpc/src/modules/interest-group/interest-group-router.ts
- packages/gateway-trpc/src/modules/job-listing/job-listing-router.ts
- packages/gateway-trpc/src/modules/mark/mark-router.ts
- packages/gateway-trpc/src/modules/offline/offline-router.ts
Quite a few links on the website breaks now because these were made private. Job listings in particular
> Make most query endpoints public procedures

- apps/web/src/app/events/components/AttendanceCard/AttendanceCard.tsx
ai-generert:
This PR conditionally renders the TicketButton component only when a user is attending an event and has a reserved spot. It extracts the queue position and attendance status into variables for better readability and reuse, then uses these variables to determine when to show the ticket button. This ensures tickets are only available to confirmed attendees with reserved spots, not to those on the waiting list.
> Only show ticket button for reserved attendees

- tools/shell/src/index.ts
- tools/shell/src/services.ts
For å kunne importere core og prisma i andre filer uten at repl'en starter
> Factor out instantiating core and prisma from the repl entrypoint file

- apps/web/src/app/events/[slug]/[eventId]/page.tsx
- apps/web/src/app/events/page.tsx
- apps/web/src/app/for-bedrifter/page.tsx
- apps/web/src/app/layout.tsx
- apps/web/src/components/Footer/Footer.tsx
- apps/web/src/components/molecules/EventsViewToggle/index.tsx
- apps/web/src/components/organisms/EventList/index.tsx
- apps/web/src/components/views/JobListingView/JobListingView.tsx
- apps/web/src/components/views/ProfileView/index.tsx
Removes unnecessary manual padding visible in easily accessible OW5 pages. Previous PRs affecting the navbar and footer introduced duplicated spacing between the navbar and page content. This change reduces that excess spacing on some of the affected pages
> Make layout spacing more consistent

- packages/oauth2/src/session.ts
The type here does not work for me locally. I won't pretend i understand this fully, but chat says:
Node.js’s Buffer is not strictly an ArrayBufferView according to TypeScript’s (and the Web Crypto API’s) types, even though both are binary data.
The error comes up because you’re passing a Buffer to something that wants an ArrayBufferView—for example, crypto.createSecretKey() in Node.js expects an ArrayBufferView, and Buffer isn’t always directly assignable in TypeScript’s view.
> Fix type oauth2 type issue

- apps/rpc/src/modules/feide/feide-groups-error.ts
- apps/rpc/src/modules/feide/feide-groups-repository.ts
- apps/rpc/src/modules/user/user-service.ts
This prevents the procedure from crashing if the token had expired.
> Check for expired Feide access token before continuing

- apps/rpc/src/instrumentation.ts
- apps/rpc/src/trpc.ts
Instead, we give them a OpenTelemetry trace ID they can provide to us if
need be. We still get the error reported on our side.
> Do not leak error details to the client

- apps/rpc/src/modules/event/event-repository.ts
- apps/rpc/src/modules/event/event-router.ts
- apps/rpc/src/modules/event/event-service.ts
- apps/web/src/app/arrangementer/[slug]/[eventId]/page.tsx
- apps/web/src/app/arrangementer/components/EventList.tsx
Hides all events in event list with a parentId unless you are an attendee at the parentEvent or `alwaysShowChildEvents` prop is true. Does not hide from calendar
This is meant to be updated and worked on in the future
> Add basic frontend for child parent events

- apps/rpc/src/modules/event/attendance.e2e-spec.ts
- apps/rpc/src/modules/event/event.e2e-spec.ts
- apps/rpc/vitest-integration.config.ts
- biome.json
Turns off fileParallelism in Vitest to avoid cross-contamination for now. Ideally, each test should run using its own test database from testcontainers.
> Fix broken and flaky tests

- apps/rpc/src/modules/event/attendance-router.ts
New attendance updates were being sent to all existing events since no filtering by attendanceId was being done.
> SSE attandance not filtering by attendanceId

- apps/web/src/components/Navbar/ProfileMenu.tsx
Opening the profile dropdown logs the user out in the background because of link prefetch
> Fix logout link prefetch causing logout

- apps/web/src/app/innstillinger/profil/form.tsx
- packages/ui/src/atoms/Textarea/Textarea.tsx
The old one was practically unusable because of the h-15
> Give more space to textarea input on profile page

- package.json
- pnpm-lock.yaml
This was previously used when we ran on Vercel in the Vercel config.
> Remove unused turbo-ignore dependency

- apps/web/src/app/arrangementer/components/EventFilters.tsx
- apps/web/src/app/arrangementer/components/EventList.tsx
- apps/web/src/app/arrangementer/page.tsx
- packages/ui/src/atoms/Select/Select.tsx
Adds filters for type and organizing group, and an option to group the list by category or date.
On mobile the filters takes up a lot of space so maybe we should hide all of them except the search?
> Add more filters to event list

- apps/rpc/resources/email/event_attendance.mustache
- apps/rpc/src/modules/email/email-template.ts
- apps/rpc/src/modules/event/attendance-service.ts
- packages/db/package.json
- pnpm-lock.yaml
This cannot be merged right now, because this NEEDS an SQS queue to fulfill because there is a 14 mails per seconds limit on SES for our account.
> Send transactional email upon event registration

- apps/rpc/src/bin/server.ts
- apps/rpc/src/modules/core.ts
- apps/rpc/src/modules/task/task-executor.ts
The entire lifecycle of the background worker can be controlled by the AbortController.
> Remove `stop` method from TaskExecutor

- apps/rpc/src/aws.ts
- apps/rpc/src/modules/email/email-service.ts
- apps/rpc/src/modules/task/task-executor.ts
- apps/rpc/src/modules/user/user-service.ts
- apps/rpc/src/trpc.ts
Slight adoptation of the RPC spans naming described in https://opentelemetry.io/blog/2025/how-to-name-your-spans/
> Consistently name OpenTelemetry spans

- apps/rpc/src/modules/core.ts
- apps/rpc/src/modules/workspace-sync/workspace-service.ts
Previously this read configuration from the global. It should always read it as a dependency. Another benefit is that typing the dependency as `ConfigurationWithGoogleWorkspace` means that none of the credential values are nullable.
> Fix dependency injection in WorkspaceService

- apps/rpc/src/aws.ts
- apps/rpc/src/bin/repl.ts
- apps/rpc/src/bin/server.ts
- apps/rpc/src/configuration.ts
- apps/rpc/src/modules/core.ts
- apps/rpc/src/modules/event/attendance-router.ts
- apps/rpc/src/modules/event/attendance-service.ts
- apps/rpc/src/modules/event/attendance.e2e-spec.ts
- apps/rpc/src/modules/event/event-service.ts
- apps/rpc/src/scripts/give-me-staff.ts
- apps/rpc/src/scripts/migrate-articles-from-ow4.ts
- apps/rpc/src/scripts/migrate-companies.ts
- apps/rpc/src/scripts/migrate-event-ids.ts
- apps/rpc/src/scripts/migrate-events.ts
- apps/rpc/src/scripts/migrate-groups-from-ow4.ts
- apps/rpc/src/scripts/migrate-offlines-from-ow4.ts
- apps/rpc/src/scripts/migrate-users-from-ow4.ts
- apps/rpc/src/scripts/seed-workspace-ids.ts
- apps/rpc/vitest-integration.setup.ts
- packages/types/src/attendance.ts
Moves all logical checks for attendance requirements into separate function. In the long term, the client should use this function instead of calculating all of the values on its own. Enables a single source of truth for attendance checks.
Also fixed up integration tests so they pass
> Move registration availability into separate service function

- apps/rpc/src/modules/task/task-executor.ts
This only prints "Running task" due to the formatting, and we don't really need this.
> Remove unnecessary log line in task-executor.ts

- apps/dashboard/src/app/(internal)/job-listing/[id]/edit-card.tsx
- apps/dashboard/src/app/(internal)/job-listing/write-form.tsx
- apps/rpc/src/mock.ts
- apps/web/src/app/karriere/[id]/page.tsx
- apps/web/src/app/karriere/page.tsx
- packages/db/prisma/migrations/20251005130233_rename_deadline_asap_to_rolling_admission/migration.sql
- packages/db/prisma/schema.prisma
- packages/db/src/fixtures/job-listing.ts
* Renames joblisting#deadlineAsap to rollingAdmission
* Uses joblisting#start instead of createdAt to show when the jobListing was posted
* Hides start and end in karriere/[id] because Bedkom asked for it
closes MONO-759
> Rename joblisting deadlineAsap

- apps/web/src/app/arrangementer/[slug]/[eventId]/page.tsx
- apps/web/src/app/arrangementer/components/AttendanceCard/AttendanceCard.tsx
- apps/web/src/app/arrangementer/components/AttendanceCard/EventRules.tsx
- apps/web/src/app/profil/[profileSlug]/components/PenaltyDialog.tsx
- apps/web/src/app/profil/[profileSlug]/page.tsx
- apps/web/src/utils/penalty-rules.tsx
- packages/ui/src/molecules/Dialog/Dialog.tsx
Added "EventRules" for explaining rules tied to events. Specifically the Mark/Penalty rules
- Added EventRules
- Updated `penalty-rules.tsx` to the new current rules
- Forwared props from Button into AlertCancel for easier styling and for preventing "Expected one parent element"-error
- Moved `TimeLocationBox` before `AttendenceCard` because the majority of "event-checking" are for seeing the date & time
- Styled for both light and darkmode
> Add mark rules
