src/components/atoms/stories/Heading.stories.tsx

These are already styled from typography.ts

feat: create heading components

---

.storybook/preview.tsx
package.json
src/components/atoms/stories/Card.stories.tsx
src/styles/components/cards.ts
src/styles/components/index.ts
src/styles/global.ts

I added some good looking cards babyyy
elevated:
outlined:

feat: add cards components

---

apps/ow-api/.eslintrc
apps/ow-api/package.json
apps/web/.eslintrc
apps/web/package.json
package.json
packages/eslint-config-ow/index.js
packages/eslint-config-ow/package.json
yarn.lock

- creates a library in packages for eslint config
- import and extend it in other packages
- maybe look to publish it?

Move eslint config to it's own package

---

packages/ow-ui/package.json
packages/ow-ui/src/components/Button/Button.stories.tsx
packages/ow-ui/src/components/Button/Button.tsx
packages/ow-ui/src/components/ModalDialog/ModalDialog.stories.tsx
packages/ow-ui/src/components/ModalDialog/ModalDialog.tsx
packages/ow-ui/src/components/ModalDialog/index.tsx
yarn.lock

:lipstick: #115 add alert modal component

---

packages/ow-ui/package.json
packages/ow-ui/src/components/Toggle/Toggle.stories.tsx
packages/ow-ui/src/components/Toggle/Toggle.tsx
packages/ow-ui/src/components/Toggle/index.tsx
yarn.lock

:lipstick: #105 add toggle component

---

turbo.json

fix: disable caching for storybook turbo task

---

.gitignore
apps/web/package.json
apps/web/src/index.test.ts
apps/web/vitest.config.ts
apps/web/vitest.setup.ts
yarn.lock

Closes: #139 
**Changelog**
- Setup Vitest
- Add sample test
- Setup code coverage

test: Setup vitest

---

apps/web/package.json
apps/web/tsconfig.json
apps/web/vitest.config.ts
yarn.lock

- Pipeline crashes since apps;/web doesn't have vite. Adds vite as a dependency

add vite to web app

---

apps/ow-api/src/modules/company/__test__/company-service.spec.ts
apps/ow-api/src/modules/company/company-repository.ts
apps/ow-api/src/modules/company/company-service.ts
apps/ow-api/src/modules/company/company.ts
packages/ow-db/prisma/migrations/20220928182718_/migration.sql
packages/ow-db/prisma/schema.prisma
packages/ow-db/src/seed/company.ts

Closes: #
- Updated the company class
- Added setters and getters for company objects
- Added tests
Run yarn test (woah!)

Company users

---

apps/web/src/components/organisms/Navbar/DesktopNavigation.tsx
apps/web/src/components/organisms/Navbar/Navbar.tsx
apps/web/src/components/organisms/Navbar/useWindow.tsx

Closes: #82 
- Remove links to external pages
- Add opacity to navbar backgroundcolor
- Add backdrop blur

Navbar component

---

packages/config/tailwind-preset.js
packages/ow-ui/package.json
packages/ow-ui/src/components/Checkbox/Checkbox.stories.tsx
packages/ow-ui/src/components/Checkbox/Checkbox.tsx
packages/ow-ui/src/components/Input/TextInput.tsx
yarn.lock

Closes: #205 
- Changed checkbox to tailwind style
- uses the tailwindcss-radix data toggles to style its state
- Follows radix-ui colors for background, hover, focus etc.

Tailwind checkbox in Design system

---

apps/ow-api/package.json
apps/ow-api/src/index.ts
apps/ow-api/src/modules/event/__test__/event-service.spec.ts
apps/ow-api/src/modules/event/event-repository.ts
apps/ow-api/src/modules/event/event-router.ts
apps/ow-api/src/modules/event/event-service.ts
apps/ow-api/src/modules/event/event.ts
apps/ow-api/src/router.ts
apps/ow-api/src/server.ts
apps/ow-api/src/trpc.ts
apps/ow-api/vitest.config.ts
packages/ow-db/prisma/migrations/20221012150028_add_event_model/migration.sql
packages/ow-db/prisma/schema.prisma
yarn.lock

Closes: #...
- Added EventService + EventRepository
- Implemented TRPC Gateway
`yarn test`

feat: implement service for creating plain events

---

packages/ow-ui/package.json
packages/ow-ui/src/components/Alert/Alert.stories.tsx
packages/ow-ui/src/components/Alert/Alert.tsx
packages/ow-ui/src/components/Alert/AlertIcon.tsx
yarn.lock

Closes: #213
- Updates the color of the alert to dark mode
- Adds the option to add children for body

Redesign Alert component in design system

---

apps/storybook/.storybook/preview.jsx
apps/web/src/components/views/CompanyView/index.tsx
packages/config/tailwind-preset.js
packages/ow-db/package.json
packages/ow-db/src/index.ts
packages/ow-ui/src/components/Button/Button.stories.tsx
packages/ow-ui/src/components/Button/Button.tsx
packages/ow-ui/src/components/ModalDialog/ModalDialog.tsx

Closes: #218
- Added the variants: subtle, light, solid
- nonInteractive can be used when disabled
- Buttons uses the radix colors

Redesign Button

---

.vscode/settings.json
apps/storybook/.storybook/preview-head.html
apps/web/package.json
apps/web/src/components/molecules/CompanyAdListItem/CompanyAdListItem.tsx
apps/web/src/components/views/ArticleView.tsx
packages/ow-ui/src/components/Badge/Badge.stories.tsx
packages/ow-ui/src/components/Badge/Badge.tsx
yarn.lock

- Redesign the badges
- Creates a badge with three variants, subtle, filled and outline

Redesign Badge component

---

apps/web/src/pages/auth/signin.tsx
packages/ow-ui/src/components/Button/Button.tsx

- Adds a gradient variant for buttons. 
- Changes the signin page to use this variant

Gradient button variant

---

apps/ow-api/src/modules/auth/auth-router.ts
apps/ow-api/src/router.ts
apps/ow-api/src/server.ts
apps/ow-api/src/trpc.ts
apps/web/src/pages/auth/signin.tsx

Moves the signing mutation into the auth namespace and merges with the event router

refactor: merge auth and event trpc routers

---

apps/ow-api/src/router.ts
apps/ow-api/src/server.ts
apps/ow-api/src/trpc.ts

fix: avoid circular dependency in trpc

---

packages/ow-ui/src/components/Button/Button.stories.tsx

- Create gradient button variant

add gradient variant for button

---

apps/db-migrator/src/index.ts
packages/ow-db/src/migrations/0001_create_user_and_auth.ts
packages/ow-db/src/migrations/0002_create_company.ts
packages/ow-db/src/migrations/0003_create-event.ts
packages/ow-db/src/types/index.ts

Closes: #238
- changes to pascalcase for table names

refactor(db): rename tables to to use pascal case

---

apps/dashboard/package.json
apps/db-migrator/package.json
apps/docs/package.json
apps/ow-api/package.json
apps/storybook/package.json
apps/web/package.json
pnpm-lock.yaml

build: upgrade typescript to 4.9.4

---

packages/ow-ui/package.json
packages/ow-ui/src/components/Accordion/Accordion.stories.tsx
packages/ow-ui/src/components/Accordion/Accordion.tsx
packages/ow-ui/src/components/Accordion/AccordionComponents.tsx
packages/ow-ui/src/components/Accordion/index.tsx
packages/ow-ui/src/components/Alert/Alert.stories.tsx
packages/ow-ui/src/utils.ts
pnpm-lock.yaml

Closes: #295 
- Add accordion component to design system
See if the component works properly on storybook

Feat accordion

---

apps/db-migrator/src/seed.ts
packages/api/src/modules/event/event-repository.ts
packages/ow-db/src/types/company.ts
packages/ow-db/src/types/event.ts
packages/types/src/event.ts

Closes: #304 
Doesn't actually need any changes in migrations because this code wouldn't work in the first place lol

fix: rename table names to Id

---

apps/web/src/components/views/CareerAdView.tsx

fix(frontend): Fixing career ad pages

---

apps/dashboard/src/app/event/EventCreationModal.tsx
packages/ow-db/src/migrations/0005_event_types.ts
packages/ow-db/src/types/event.ts
packages/types/src/event.ts

feat: implement event type as an enum

---

apps/dashboard/src/app/committee/page.tsx
apps/dashboard/src/app/event/EventCreationModal.tsx
apps/dashboard/src/app/event/EventDetailsModal.tsx
apps/dashboard/src/app/event/page.tsx
packages/api/package.json
packages/api/src/context.ts
packages/api/src/modules/committee/__test__/committee-service.spec.ts
packages/api/src/modules/committee/committee-repository.ts
packages/api/src/modules/committee/committee-router.ts
packages/api/src/modules/committee/committee-service.ts
packages/api/src/modules/company/__test__/company-service.spec.ts
packages/api/src/modules/company/company-repository.ts
packages/api/src/modules/company/company-router.ts
packages/api/src/modules/company/company-service.ts
packages/api/src/modules/event/__test__/event-service.spec.ts
packages/api/src/modules/event/attendee-repository.ts
packages/api/src/modules/event/attendee-service.ts
packages/api/src/modules/event/event-repository.ts
packages/api/src/modules/event/event-router.ts
packages/api/src/modules/event/event-service.ts
packages/api/src/utils/db-utils.ts
packages/api/tsconfig.json
packages/api/vitest.config.ts
pnpm-lock.yaml

- More fluent way to paginate lists of data
- Fixed broken vitests
- Converted companies to the new class service format

Add pagination and refactor services into classes

---

.github/workflows/chromatic.yml
.github/workflows/ci.yml
package.json
pnpm-lock.yaml

Sets a package.json requirement for PNPM 8.x and adopts the new lockfile format

build: pnpm version to 8.x

---

apps/dashboard/package.json
apps/dashboard/src/app/event/page.tsx

feat: show commitee name in event table

---

apps/db-migrator/src/fixture.ts
apps/db-migrator/src/fixtures/attendee.ts
apps/db-migrator/src/fixtures/user.ts
apps/web/src/pages/api/webhooks/clerk.ts
packages/api/index.ts
packages/api/package.json
packages/api/src/handlers/clerk-webhook.ts
packages/api/src/modules/auth/auth-router.ts
packages/api/src/modules/auth/user-repository.ts
packages/api/src/modules/auth/user-service.ts
packages/api/src/modules/services.ts
packages/ow-db/src/migrations/0001_create_user_and_auth.ts
packages/ow-db/src/migrations/0003_create-event.ts
packages/ow-db/src/migrations/0004_create_marks.ts
packages/ow-db/src/types/user.ts
packages/types/src/user.ts
pnpm-lock.yaml

- This webhook adds the user to our database when the event, `user.created` is sent.
- Removes all unecesarry fields from the user object
- Consider renaming user to Tenant?
- Rewrites some old migrations, so probably need to fix the migrations

Add a clerk webhook to add the user ID to local database on registration

---

apps/db-migrator/src/index.ts
packages/ow-db/src/migrations/0003_create_event.ts
packages/ow-db/src/migrations/0005_event_types.ts

Fixes minor issues in migrations.

Fix migrations

---

packages/api/src/modules/committee/committee-repository.ts

Not much to see here. Code is self explanatory.

Fix insert values of committee

---

infra/neon/.terraform.lock.hcl
infra/neon/main.tf
infra/neon/providers.tf
infra/neon/terraform.tf

Depends on #421 
Also deployed to dev environment

Create neon.tech projects and databases from Terraform

---

.github/renovate.json

renovate bot broke it with automerge

dont bump package manager in renovate

---

apps/db-migrator/package.json
apps/sanity/package.json
apps/web/package.json

All packages were good from before

fix: consistently name all apps

---

README.md

add note on environment

---

apps/dashboard/src/app/MantineProvider.tsx
apps/dashboard/src/app/layout.tsx

fix: extract mantine provider into client component

---

packages/ui/package.json
packages/ui/src/components/RadioGroup/RadioGroup.stories.tsx
packages/ui/src/components/RadioGroup/RadioGroup.tsx
packages/ui/src/components/RadioGroup/index.tsx
pnpm-lock.yaml

Closes: #125 
* Add radio group component 
Check storybook

Add RadioGroup component

---

apps/dashboard/src/app/(dashboard)/event/page.tsx
apps/dashboard/src/app/(dashboard)/user/page.tsx
apps/dashboard/src/app/ApplicationShell.tsx
apps/dashboard/src/components/molecules/company-name/event-committees.tsx
apps/dashboard/src/modules/company/use-company-table.tsx

Also removes things removed in #597 because it's now fixed

Use Link component from Next in all dashboard links

---

apps/dashboard/src/app/(dashboard)/punishment/page.tsx
apps/dashboard/src/modules/punishment/queries/use-count-users-with-mark-query.ts
apps/dashboard/src/modules/punishment/queries/use-punishment-all-query.ts
apps/db-migrator/src/fixture.ts
apps/db-migrator/src/fixtures/personal-mark.ts
packages/core/src/modules/mark/personal-mark-repository.ts
packages/core/src/modules/mark/personal-mark-service.ts
packages/gateway-trpc/src/modules/mark/mark-router.ts
packages/gateway-trpc/src/modules/mark/personal-mark-router.ts
packages/gateway-trpc/src/router.ts
packages/types/src/mark.ts

Dashboard page listing all marks

Simple punishment page

---

apps/dashboard/src/app/(dashboard)/punishment/[id]/page.tsx
apps/dashboard/src/modules/company/queries/use-company-events-all-query.ts
packages/core/src/modules/mark/personal-mark-repository.ts
packages/core/src/modules/mark/personal-mark-service.ts

Got absolutely blasted and rekt by automerge

Fix comments from #631

---

apps/db-migrator/package.json
apps/db-migrator/src/seed.ts
pnpm-lock.yaml

We initially wanted to use it for fake data in test, but we found out it's significantly better to populate a test database with handmade fixtures

Remove faker package

---

infra/.terraform.lock.hcl
infra/modules/neon-project/neon.tf
infra/modules/neon-project/variables.tf
infra/modules/neon-project/versions.tf
infra/providers.tf
infra/terraform.tf
infra/vengeful-vineyard.tf

Created a google workspace user with email/password in Doppler

Add terraform provider for neon

---

infra/.terraform.lock.hcl
infra/auth.tf
infra/doppler.tf
infra/modules/aws-docker-lambda/lambda.tf
infra/modules/aws-docker-lambda/variables.tf
infra/modules/aws-s3-public-bucket/cloudfront.tf
infra/modules/aws-s3-public-bucket/iam.tf
infra/modules/aws-s3-public-bucket/outputs.tf
infra/modules/aws-s3-public-bucket/s3.tf
infra/providers.tf
infra/vengeful-vineyard.tf

See https://github.com/dotkom/vengeful-vineyard/pull/267
Depends on #661

Deploy vengeful vineyard to AWS Lambda/API Gateway

---

infra/modules/vercel-application/variables.tf
infra/modules/vercel-application/vercel.tf
infra/rif/.terraform.lock.hcl
infra/rif/doppler.tf
infra/rif/main.tf
infra/rif/providers.tf
infra/rif/route53.tf
infra/rif/terraform.tf
infra/vengeful-vineyard/main.tf

Deploys it again into /infra/rif

Deploy interest form to Vercel

---

README.md

In case it ever happens again (:crossed_fingers:) we have a small guide for fixing it

Add documentation on syncing ow users

---

apps/web/src/components/layout/ProfileLayout.tsx
apps/web/src/components/molecules/StudentProgress/StudentProgress.tsx
apps/web/src/components/organisms/Navbar/components/profile/ProfileMenu/MobileMenuContainer.tsx
apps/web/src/components/organisms/Navbar/components/profile/ProfileMenu/ProfileMenuContainer.tsx
apps/web/src/components/organisms/Navbar/components/profile/ProfileMenu/ProfileMenuItem.tsx
apps/web/src/components/views/ProfileView/components/ProfileLanding.tsx

Closes: #...
- made ProfileLanding responsive
- made ProfileLayout responsive
- added resized StudentProgress for smaller screens
- added MobileMenuContainer for displaying profile menu links for smaller screens
- Run monoweb
- Navigate to <code>/profile</code>
- Resize window

Make profile view responsive

---

infra/core/.terraform.lock.hcl
infra/core/main.tf
infra/core/providers.tf
infra/core/terraform.tf
infra/modules/vercel-application/variables.tf
infra/modules/vercel-application/vercel.tf
package.json
packages/pgx-ulid/.gitignore
packages/pgx-ulid/build.sh
packages/pgx-ulid/package.json
pnpm-lock.yaml

Adds a postgres image with the pgx_ulid extension installed. It's pushed to public ECR

Add public ecr repository for pgx-ulid

---

packages/auth/src/auth-options.ts
packages/core/src/utils/db-utils.ts

Seems like intellij autoimport failed me :sob:

Add missing import for NotFoundError

---

apps/rif/src/app/form-schema.ts
apps/rif/src/app/form.tsx
apps/rif/src/app/page.tsx
apps/rif/src/app/takk/page.tsx
packages/emails/src/emails/interest-form-for-bedkom.tsx
packages/emails/src/emails/interest-form-for-company.tsx
packages/ui/src/components/Checkbox/Checkbox.tsx
packages/ui/src/components/Input/TextInput.tsx

Refer to response email from bedkom with feedback for the page.
- Removed job listing from the schema, with a text message instructing companies to directly contact bedkom
- Changed the input form color to white

Remove job listing from interest form

---

infra/modules/vercel-application/vercel.tf

See https://github.com/dotkom/monoweb/pull/686 for example

Skip vercel build on Renovate PRs

---

apps/web/package.json
pnpm-lock.yaml

Remove chromatic

---

.dockerignore
apps/dispatcher-auth/package.json
apps/dispatcher-auth/ship.json
package.json
packages/logger/src/index.ts
pnpm-lock.yaml
tools/ship/package.json
tools/ship/src/aws.ts
tools/ship/src/config.ts
tools/ship/src/docker.ts
tools/ship/src/index.ts
tools/ship/src/logger.ts
tools/ship/tsconfig.json

Shorthand tool for:
1. Logging into ECR
2. Building the Docker image
3. Pushing the Docker image to ECR
4. Updating the lambda code with the image
From the root directory, invoke Ship and specify which app to deploy. It will read the ship.json config file in the target directory.
```sh
pnpm ship deploy apps/dispatcher-auth --env dev
```
Example ship.json configuration
```json
{
"imageName": "dispatcher-auth",
"version": "latest",
"environments": [
{
"name": "dev",
"ecrRepository": "891459268445.dkr.ecr.eu-north-1.amazonaws.com/dispatcher-auth-dev",
"functionName": "dispatcher-auth-dev",
"dockerfile": "apps/dispatcher-auth/Dockerfile"
}
]
}
```

Create deploy tool for deploying AWS Lambda Docker containers

---

packages/auth/src/auth-options.ts
packages/auth/src/dashboard.app.ts
packages/auth/src/web.app.ts

Next Auth doesn't pick this up automatically anymore

Specify Next Auth JWT secret manually

---

infra/README.md
infra/grades/terraform.tf
infra/rif/terraform.tf
infra/vengeful-vineyard/terraform.tf
infra/web/terraform.tf
tools/ship/src/config.ts
tools/ship/src/index.ts

Remove staging environment

---

infra/cognito/main.tf
infra/core/main.tf
infra/core/route53.tf

Had to move null record to core infra

Deploy cognito to production environment

---

apps/rif/src/app/form-schema.ts
apps/rif/src/app/form.tsx
infra/rif/main.tf
packages/emails/src/emails/interest-form-for-bedkom.tsx
packages/emails/src/emails/interest-form-for-company.tsx

Add option for events with FeminIT to interest form

---

infra/modules/vercel-application/vercel.tf

Remove prevention configuration against renovate vercel deploys

---

infra/grades_v2/.terraform.lock.hcl
infra/grades_v2/main.tf
infra/grades_v2/providers.tf
infra/grades_v2/terraform.tf

Contains only a database for now

Create postgres database for Grades v2

---

docs/infrastructure/gateway-email.md
docs/infrastructure/gradestats.md
docs/infrastructure/index.md
docs/infrastructure/monoweb.md
docs/infrastructure/onlineweb4.md
docs/infrastructure/rif.md
docs/infrastructure/vengeful-vineyard.md
infra/modules/neon-project/README.md

Goes into detail into each application/service's deployment strategy and links to the tf configs and source for each.

Create documentation for current infrastructure state

---

packages/core/vitest-integration.setup.ts
packages/db/src/migrations/0021_create_offline.js
packages/db/src/migrations/0022_add_article.js

Also prints an error now instead of silently failing

Fix integration tests

---

apps/web/src/components/organisms/Navbar/NavigationMenu.tsx

Fix problem where navbar submenus close before you are able to interact with them when moving the cursor slowly
Uploading Screen Recording 2024-02-17 at 17.31.40.mov…
https://github.com/dotkom/monoweb/assets/16722718/865d940b-2ec8-4a87-8e98-fb13f2c5acfe

Fix navbar hover bug

---

infra/auth0/logging.tf
infra/auth0/main.tf
infra/auth0/providers.tf

This removes Vengeful-doppler-sync until that has been sorted out.
Has already been applied.

Add Auth0 Staging-env

---

packages/db/src/db.generated.d.ts
packages/db/src/migrator.ts

Migrations won't run when the migrations folder path has any URL encoded characters. This is a problem if the repo is inside a folder with a space character (definitely not me 👀)

add uri decoder to migration folder path

---

apps/rif/src/app/form.tsx
apps/rif/src/app/takk/page.tsx

Fix minor typos in company interest form

---

CONTRIBUTING.md

Just so it's clear and easy to see :)

Document which applications run where

---

infra/auth0/appkom.tf

Add android config for appkom

---

apps/web/src/components/organisms/Navbar/MobileNavigation.tsx

No way this was intentional lol

Swap mobile navbar icons

---

README.md

Fix developer guide link in README.md

---

apps/brevduen/biome.json
apps/dashboard/biome.json
apps/invoicification/biome.json
apps/rif/biome.json
apps/web/biome.json
biome.json
packages/auth/biome.json
packages/config/package.json
packages/core/biome.json
packages/db/biome.json
packages/emails/biome.json
packages/env/biome.json
packages/gateway-edge-nextjs/biome.json
packages/gateway-trpc/biome.json
packages/logger/biome.json
packages/types/biome.json
packages/ui/biome.json
tools/migrator/biome.json
tools/ship/biome.json

Fixes a bug in the Biome for VSCode extension where format on save didn't work

Relocate biome.json to project root

---

apps/web/src/app/settings/components/ChangeAvatar.tsx
apps/web/src/app/settings/password/page.tsx
apps/web/src/components/organisms/Navbar/ProfileMenu.tsx
apps/web/src/components/views/SettingsView/components/SettingsLanding.tsx
apps/web/src/components/views/SettingsView/components/SettingsPassword.tsx
packages/ui/src/components/Input/TextInput.tsx

Closes: #...
- [NEW]: Created a password view base on Figma design
- [MOD]: Changed SettingsLanding to use users given- and family name
- [MOD]: TextInput made client-component
- [FIX]: Navbar sidemenu bug where link is just on text and not the whole hover div

Create password view

---

infra/auth0/appkom.tf

Requested by appkom, see shared slack channel

Add sha256 fingerprint to the appkom auth0 client

---

infra/auth0/appkom.tf
infra/auth0/main.tf

Add appkom-autobank

---

infra/auth0/branding/universal_login_base.html

Update login screen

---

biome.json

Add db.generated.d.ts to biome ignore

---

packages/db/src/migrations/0003_create_event.js
packages/db/src/migrations/0022_yeet_cognito.js

Fix fucked migrations

---

apps/web/src/app/events/[id]/page.tsx
apps/web/src/app/events/components/TicketButton.tsx
apps/web/src/app/events/components/queries.ts

Fixes broken types regressed from c61af771d94228b8b227c31ff05578fa64f6caf5

Fix broken types from c61af771d94228b8b227c31ff05578fa64f6caf5

---

apps/brevduen/package.json
apps/dashboard/package.json
apps/invoicification/package.json
apps/rif/package.json
apps/web/package.json
package.json
packages/auth/package.json
packages/config/package.json
packages/core/package.json
packages/db/package.json
packages/emails/package.json
packages/env/package.json
packages/gateway-edge-nextjs/package.json
packages/gateway-trpc/package.json
packages/types/package.json
packages/ui/package.json
pnpm-lock.yaml
tools/migrator/package.json
tools/shell/package.json

Bump TypeScript to 5.4.5

---

.github/workflows/ci.yml

Freeze pnpm install in ci.yml

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml

Pnpm 9 was released two weeks ago [v9.0.0](https://github.com/pnpm/pnpm/releases/tag/v9.0.0), with a new lock format

upgrade lock file version from 6 to 9

---

package.json

https://github.com/vercel/turbo/issues/7993

Set corepack package manager

---

.github/workflows/ci.yml
apps/brevduen/Dockerfile
apps/brevduen/package.json
apps/dashboard/package.json
apps/invoicification/package.json
apps/rif/package.json
apps/web/package.json
package.json
packages/core/package.json
packages/core/tsconfig.json
pnpm-lock.yaml
tsconfig.json

Node 18 is in maintenance mode, while 20 is in active development. We should use 20.

Update to Node.js 20.x

---

package.json

Adds some more package metadata to the root package.json

Add some more package.json metadata

---

.gitignore
apps/web/src/app/events/[id]/page.tsx
apps/web/src/app/events/components/EventHeader.tsx
apps/web/src/app/events/components/EventInfoBox.tsx
apps/web/src/app/layout.tsx
packages/config/tailwind-preset.js
packages/config/typography.css
packages/core/src/modules/core.ts
packages/core/src/modules/event/event-service.ts

WIP Event detail page

---

infra/auth0/appkom.tf

Change in #922 was missing a double quotes lol

Add missing quote

---

infra/auth0/actions.tf
infra/auth0/branding/universal_login_base.html
infra/auth0/inputs.tf
infra/auth0/main.tf

Update tf to reflect applied

---

.github/renovate.json

Revert "Disable renovate until it can handle lockfile 9"

---

package.json
packages/core/package.json
pnpm-lock.yaml
turbo.json

Turbo2 and bump testcontainers

---

package.json

Fix web build command not working.
This made CI not work

Fix web build command

---

apps/web/src/components/molecules/CompanyAdListItem/CompanyAdListItem.tsx
apps/web/src/components/molecules/CompanyFiltersContainer/CompanyFiltersContainer.tsx
apps/web/src/components/views/JobListingView/JobListingView.tsx
packages/config/typography.css

refactor: updated responsiveness for listing page

---

apps/dashboard/src/modules/attendance/components/attendance-page/AttendanceForm.tsx
apps/invoicification/Dockerfile
apps/invoicification/next.config.mjs
apps/invoicification/package.json
apps/invoicification/src/app/health/route.ts
apps/rif/src/app/health/route.ts
pnpm-lock.yaml

Also adds docker build for invoicification

Add healthcheck routes to rif and invoicification

---

apps/dashboard/package.json
apps/web/package.json
pnpm-lock.yaml
turbo.json

Turbopack didn't work because of problems with the aws sdk and postgres, but i fixed it by adding them as explicit dependencies of web and dashboard. This makes hot reload super smooth

Switch web and dashboard to turbopack

---

apps/invoicification/src/app/form-schema.ts
apps/invoicification/src/app/form.tsx
packages/emails/src/emails/invoice-form-for-bedkom.tsx

This PR:
* Removes Tech Talks from invoicification (by request of bedkom)
* Fixes column widths in email sent to bedkom
* Small refactor
Before:
After:

Remove tech talks from invoicification

---

justfile

Should fix the broken CI commands

Do not run doppler for building

---

apps/rpc/src/env.ts
apps/rpc/src/index.ts
packages/db/src/index.ts
packages/environment/src/index.d.ts
tools/migrator/src/db.ts
tools/migrator/src/env.ts

We can now provide the certificate bundle so that prod can connect lol

Support optional certificate authority for database connection

---

apps/brevduen/Dockerfile
apps/dashboard/Dockerfile
apps/invoicification/Dockerfile
apps/rif/Dockerfile
apps/rpc/Dockerfile

This should be totally OK to do, and maybe SonarCloud will be happy again

Tighten permissions in Dockerfiles

---

infra/auth0/main.tf

Remove prod resources for feide in auth0

---

apps/rpc/package.json
pnpm-lock.yaml

This reverts commit 378b49da284e57450dad1843e623fa072476d36d.
Closes: #...

Revert "Update dependency @fastify/cors to v10 (#1129)"

---

CONTRIBUTING.md
README.md

Updated readme to main readme file and contributed.
Think how to run locally should be in the main readme file to keep it simple for beginners.

Readme file

---

apps/rpc/package.json
pnpm-lock.yaml

rpc load env file variables

---

infra/auth0/main.tf

This looks like it works to me, I was able to apply without causing problems

Enable passkeys in terraform

---

packages/logger/package.json
packages/logger/src/index.ts
pnpm-lock.yaml

Upgrade winston to version 3.17.x

---

apps/rpc/package.json
pnpm-lock.yaml

Move dotenv-cli to dev-dependencies

---

apps/web/src/app/career/page.tsx
packages/core/src/modules/job-listing/__test__/job-listing.e2e-spec.ts
packages/core/src/modules/job-listing/job-listing-error.ts
packages/core/src/modules/job-listing/job-listing-repository.ts
packages/core/src/modules/job-listing/job-listing-service.ts
packages/gateway-trpc/src/modules/job-listing/job-listing-router.ts

Closes: #...
- Add a query "getActive" for requesting job listings where start date <= today <= end date
- Make career page request the active job listings
- Remove incorrect validation where deadline couldn't be after the start date in Create Job Listing on dashboard
- Removed tests and error for invalid deadlines

Filtrere ut jobbannonser ute pa dato

---

packages/auth/package.json
pnpm-lock.yaml

Remove unnecessary dependencies from auth package

---

.github/workflows/deploy-staging.yml

Deploys staging rpc on main push

Deploy monoweb/rpc/staging image from main

---

apps/dashboard/package.json
apps/invoicification/package.json
apps/rif/package.json
apps/rpc/package.json
package.json

Do not specify platform for local Docker builds

---

.github/workflows/ci.yml
apps/brevduen/Dockerfile
apps/dashboard/Dockerfile
apps/invoicification/Dockerfile
apps/rif/Dockerfile
apps/rpc/Dockerfile
package.json

This reverts commit 1af819c and the one before because pnpm 9.15.7 is not available on vercel

Revert "Upgrade remaining infra to pnpm@9.15.7"

---

apps/kvittering-backend/src/core/data_types.py
apps/kvittering-backend/src/server.py
apps/kvittering-frontend/.env.local
apps/kvittering-frontend/src/components/receipt-form.tsx
apps/kvittering-frontend/src/lib/api.ts

---
name: ''
about: ''
title: ''
labels: ''
assignees: ''
---
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Report kvittering completion time

---

.github/workflows/deploy-staging.yml

See infra 
https://github.com/dotkom/terraform-monorepo/pull/183

Add staging deploy of dashboard

---

.gitignore
apps/rpc/package.json
apps/rpc/src/env.ts
apps/rpc/src/index.ts
apps/rpc/src/sentry.ts
apps/rpc/tsconfig.json
pnpm-lock.yaml

Configures Sentry's node sdk
Part of INF-6

Configure Sentry for RPC application

---

apps/web/Dockerfile
apps/web/next.config.mjs
apps/web/package.json
pnpm-lock.yaml

Builds web with rpc host/public hostname build arguments

Add dockerfile build for web

---

apps/web/src/app/company-info/page.tsx

Noen fjernet company info siden 😤😤😤😤😤

Revive Company info page

---

apps/splash-2025/package.json
apps/splash-2025/src/App.tsx
apps/splash-2025/src/components/header.tsx
apps/splash-2025/src/styles/globals.css
apps/splash-2025/tailwind.config.ts
pnpm-lock.yaml

Fix splash-2025 ci

---

apps/dashboard/package.json
apps/web/next.config.mjs
apps/web/package.json
pnpm-lock.yaml

output=standalone can build just fine on vercel too

Remove unused pg dependency and force standalone build

---

.github/workflows/ci.yml
apps/web/Dockerfile

Passes secrets from Doppler to the build action for web.

Provide web container with doppler secrets from staging

---

apps/invoicification/src/app/layout.tsx
apps/rif/src/app/layout.tsx

These apps looked a bit different because they were not using the font
from the rest of the design system

Import Fraunces and Poppins fonts in rif/invoicification

---

packages/ui/.ladle/unoptimized-link.tsx
packages/ui/package.json
packages/ui/src/components/Typography/Link.tsx
packages/ui/src/components/Typography/Typography.stories.tsx
packages/ui/tailwind.config.cjs
packages/ui/vite.config.ts
pnpm-lock.yaml

Defaults to using a NextLink under the hood. Has the same sizing options
as the regular Text component

Create polymorphic Link component

---

.npmrc
apps/dashboard/next.config.mjs
apps/web/next.config.mjs

See https://github.com/vercel/next.js/issues/68805

Shamefully hoist prisma client

---

apps/dashboard/src/app/(dashboard)/event/page.tsx

Turn event table name into link

---

packages/ui/src/components/Button/Button.tsx

Passes them as a div if there is an icon

Pass children as fragment in button

---

apps/web/src/styles/globals.css

Scuffed menu må til fordi radix er weird og fjerner scrollbar på hele siden når noen components er åpne
https://github.com/radix-ui/primitives/issues/1496
https://github.com/radix-ui/primitives/issues/3251
Kokt fra brage her https://github.com/dotkom/monoweb/blob/main/apps/invoicification/src/root.css

Fix scrollbar flickering when opening and closing menu

---

tools/shell/package.json
tools/shell/src/env.ts

There was a type error here from the createEnvironment changes yesterday
that were not caught because of this

Add missing type-check task to tools/shell

---

.github/workflows/ci.yml

Release to prod on workflow dispatch

---

.github/workflows/ci.yml
packages/oauth2/src/nextjs.ts

Currently logout does not work in staging, this attempts to fix it

Make logout work

---

apps/web/src/app/events/components/EventDescription.tsx

fixed mdx-rendering for events

fix: fixed eventdescription mdx

---

apps/web/src/app/events/[eventId]/page.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceBoxPool.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceBoxPoolSmall.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceCard.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceDateInfo.tsx
apps/web/src/app/events/components/AttendanceCard/RegistrationButton.tsx
apps/web/src/app/events/components/AttendanceCard/TicketButton.tsx
apps/web/src/app/events/components/AttendanceCard/ViewAttendeesButton.tsx
apps/web/src/app/events/components/EventHeader.tsx
apps/web/src/app/events/components/TimeLocationBox/LocationBox.tsx
apps/web/src/app/events/components/TimeLocationBox/TimeBox.tsx
apps/web/src/app/events/components/TimeLocationBox/TimeLocationBox.tsx

Fix text rendering

---

apps/web/src/components/Navbar/MobileNavigation.tsx

refactor: fixed popover closing + bigger padding

Style mobile navbar

---

apps/web/src/components/Footer/Footer.tsx
apps/web/src/components/Footer/LogoSection.tsx

Or maybe this was intended to be like this? It just looked a bit off

Align footer with header and body

---

apps/web/src/app/events/[eventId]/page.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceBoxPool.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceBoxPoolSmall.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceCard.tsx
apps/web/src/app/events/components/AttendanceCard/RegistrationButton.tsx
apps/web/src/app/events/components/AttendanceCard/mutations.ts
packages/config/tailwind-preset.js
packages/config/tailwind.css
packages/core/src/modules/attendance/attendance-repository.ts
packages/core/src/modules/attendance/attendee-repository.ts
packages/types/src/attendance/attendance-pool.ts

Implement frontend for waitlist

---

apps/web/src/app/events/components/AttendanceCard/AttendanceCard.tsx
apps/web/src/app/events/components/AttendanceCard/AttendeesList.tsx
apps/web/src/app/events/components/AttendanceCard/ViewAttendeesButton.tsx
packages/config/tailwind.css
packages/core/src/modules/attendance/attendee-service.ts

Implement attendee list

---

apps/web/src/app/events/components/AttendanceCard/AttendanceCard.tsx
apps/web/src/app/events/components/AttendanceCard/AttendeeList.tsx
apps/web/src/app/events/components/AttendanceCard/ViewAttendeesButton.tsx

Highlight self in attendee list

---

apps/web/src/app/events/[slug]/[eventId]/page.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceCard.tsx
apps/web/src/app/events/components/AttendanceCard/ViewAttendeesButton.tsx
apps/web/src/app/events/components/TimeLocationBox/ActionLink.tsx
apps/web/src/app/events/components/TimeLocationBox/LocationLink.tsx
apps/web/src/app/events/components/TimeLocationBox/TimeBox.tsx
apps/web/src/app/events/components/TimeLocationBox/TimeLocationBox.tsx

User border instead of background for event cards

---

apps/web/src/components/views/JobListingView.tsx

Finalize job listing page styling so it looks good for lightmode

---

apps/web/src/app/events/[slug]/[eventId]/page.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceBoxPoolSmall.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceCard.tsx
apps/web/src/app/events/components/AttendanceCard/AttendanceDateInfo.tsx
apps/web/src/app/events/components/AttendanceCard/TicketButton.tsx
apps/web/src/app/events/components/EventDescription.tsx
apps/web/src/app/events/components/TimeLocationBox/TimeLocationBox.tsx

This PR improves responsive design for mobile views

Make events mobile friendly

---

apps/web/src/app/events/components/AttendanceCard/RegistrationButton.tsx
apps/web/src/app/events/components/AttendanceCard/TicketButton.tsx
apps/web/src/app/events/components/AttendanceCard/ViewAttendeesButton.tsx
apps/web/src/components/molecules/ProfileMolecules/PersonalInfo.tsx
apps/web/src/components/molecules/ProfileMolecules/StudyProgressionBox.tsx
apps/web/src/components/views/SettingsView/components/SettingsLanding.tsx
packages/ui/src/atoms/Button/Button.stories.tsx
packages/ui/src/atoms/Button/Button.tsx
packages/ui/src/molecules/Dialog/Dialog.tsx

This PR:
- Updates button component with new styles, colors and variants
- Make the component easier to override (no !important), and an unstyled variant is available.
- Updates storybook to programmatically generate all buttons
rip unstyled

Update button component

---

apps/web/src/components/Navbar/Navbar.tsx
apps/web/src/components/Navbar/ProfileMenu.tsx
packages/ui/package.json
packages/ui/src/atoms/Popover/Popover.tsx
packages/ui/src/atoms/RadioGroup/RadioGroup.tsx
packages/ui/src/index.ts
pnpm-lock.yaml

Add theme toggle in navbar

---

apps/web/src/app/events/components/AttendanceCard/RegistrationButton.tsx

It already gets disabled in backend

Disable deregister button past deregister deadline

---

apps/dashboard/src/app/(dashboard)/event/components/all-users-table.tsx
packages/core/src/modules/attendance/attendance-repository.ts
packages/core/src/modules/attendance/attendee-service.ts
packages/gateway-trpc/src/modules/event/attendance-router.ts
packages/types/src/user/membership.ts
packages/types/src/user/user.ts

This PR:
- Makes admin deregistration forcefully reserve next attendee
- Refactor that should have been its own PR

Admin deregistration reserve next attendee

---

apps/web/src/app/andre-grupper/page.tsx
apps/web/src/app/events/[slug]/[eventId]/page.tsx
apps/web/src/app/interessegrupper/page.tsx
apps/web/src/app/komiteer/page.tsx
apps/web/src/app/nodekomiteer/page.tsx
apps/web/src/components/molecules/GroupListItem/index.tsx
apps/web/src/components/organisms/GroupList/index.tsx

Mainly fixes links to organizers in event view and makes committee and nodecommittee icons more visible in darkmode

Cleanup organizers in ui

---

apps/rpc/package.json
apps/rpc/src/index.ts
packages/gateway-trpc/src/context.ts
pnpm-lock.yaml

This means we don't instantiate all services at once

Only create service layer once

---

apps/web/src/app/artikler/page.tsx
apps/web/src/components/Navbar/Navbar.tsx
apps/web/src/components/molecules/ArticleFiltersContainer.tsx/index.tsx
apps/web/src/components/molecules/ArticleListItem/index.tsx
apps/web/src/components/molecules/ArticleTag/index.tsx
apps/web/src/components/organisms/ArticleList/index.tsx
apps/web/src/components/views/ArticleView/index.tsx

Articles list page

---

apps/dashboard/src/modules/group/use-group-table.tsx
apps/dashboard/src/modules/interest-group/use-interest-group-table.tsx
apps/dashboard/src/modules/offline/use-offline-table.tsx
apps/web/src/app/offline/page.tsx
apps/web/src/app/page.tsx
apps/web/src/components/molecules/OfflineCard/index.tsx
packages/core/src/modules/offline/offline-repository.ts

We should probably plan an overall design for the front page later, this is just to have them there for mvp

Show Offlines on front page

---

apps/dashboard/src/app/(dashboard)/event/[id]/attendees-page.tsx
apps/dashboard/src/app/(dashboard)/event/components/qr-code-scanner.tsx

Improve QR-code scanner UI

---

apps/brevduen/src/index.ts
apps/brevduen/src/instrumentation.ts
apps/brevduen/src/sentry.ts
apps/dashboard/src/instrumentation.ts
apps/rpc/package.json
apps/rpc/src/aws.ts
apps/rpc/src/index.ts
apps/rpc/src/instrumentation.ts
apps/rpc/src/sentry.ts
apps/web/src/instrumentation.ts
docker-compose.yml
packages/logger/package.json
packages/logger/src/index.ts
pnpm-lock.yaml

Instruments web, dashboard, brevduen, and rpc with OpenTelemetry. Also adds Jaeger UI as a local trace viewer.

Instrument core applications with OpenTelemetry

---

apps/web/src/components/Navbar/ProfileMenu.tsx
packages/gateway-trpc/src/modules/user/user-router.ts
packages/ui/src/molecules/DropdownMenu/DropdownMenu.tsx

Update profile navbar menu

---

apps/invoicification/src/app/controlled-select.tsx
apps/invoicification/src/app/form.tsx
apps/rif/src/app/checkbox.tsx
apps/rif/src/app/form-schema.ts
apps/rif/src/app/form.tsx
packages/emails/src/emails/interest-form-for-bedkom.tsx
packages/emails/src/emails/interest-form-for-company.tsx
packages/ui/src/atoms/Tooltip/Tooltip.tsx

Updated to use dotkom components

Update interest and invoice forms with new components and options

---

apps/kvittering-frontend/package.json
apps/rpc/src/modules/core.ts
apps/rpc/src/modules/event/event-repository.ts
apps/rpc/src/modules/event/event-router.ts
apps/rpc/src/modules/event/event-service.ts
apps/rpc/src/modules/event/event.e2e-spec.ts
apps/splash-2025/package.json
apps/splash-2025/src/components/events.tsx
pnpm-lock.yaml

Does not do anything related to attendance for now.

Write simple integration tests for event

---

apps/dashboard/src/app/event/[id]/page.tsx
apps/dashboard/src/app/event/components/edit-form.tsx
apps/dashboard/src/app/event/components/event-hosting-group-list.tsx
apps/dashboard/src/app/event/components/write-form.tsx
apps/dashboard/src/app/event/mutations.ts
apps/dashboard/src/app/event/page.tsx
apps/rpc/src/modules/event/event-repository.ts
apps/rpc/src/modules/event/event-router.ts
apps/rpc/src/modules/event/event-service.ts
apps/web/src/app/arrangementer/page.tsx
packages/types/src/event.ts

This PR:
- Updates event list in dashboard
- Should note that while a search bar is added, it is disabled and non-functional
- Adds a delete button to events

Update events in dashboard

---

apps/rpc/src/modules/user/user-repository.ts
packages/db/prisma/migrations/20250803115925_revert_last_migration/migration.sql
packages/db/prisma/schema.prisma

Fix broken migration

---

apps/rpc/src/aws.ts
apps/rpc/src/modules/user/user-service.ts
apps/rpc/src/trpc.ts

Execute each tRPC request inside an OpenTelemetry span

---

apps/rpc/src/modules/mark/personal-mark-service.ts
apps/web/src/app/arrangementer/[slug]/[eventId]/page.tsx
apps/web/src/app/arrangementer/components/AttendanceCard/AttendanceCard.tsx
apps/web/src/app/arrangementer/components/AttendanceCard/MainPoolCard.tsx
apps/web/src/app/arrangementer/components/AttendanceCard/PunishmentBox.tsx
apps/web/src/app/arrangementer/components/AttendanceCard/RegistrationButton.tsx
apps/web/src/app/arrangementer/components/AttendanceCard/ViewAttendeesButton.tsx
apps/web/src/app/arrangementer/components/mutations.ts
apps/web/src/app/profil/[profileSlug]/page.tsx
packages/db/prisma/schema.prisma
packages/types/src/mark.ts
packages/utils/src/holidays.ts

Delay from marks:
Delay from marks (dark mode):
Suspension from marks:
Suspension from marks (dark mode):
After you register:
Closes MONO-511

Implement punishment delay in frontend

---

apps/rpc/src/scripts/migrate-users-from-ow4.ts
packages/db/prisma/migrations/20250805120925_add_other_membership_type/migration.sql
packages/db/prisma/schema.prisma
packages/types/src/user.ts

Add script for migrating users from ow4

---

apps/web/src/app/andre-grupper/[slug]/page.tsx
apps/web/src/app/interessegrupper/[slug]/page.tsx
apps/web/src/app/komiteer/[slug]/page.tsx
apps/web/src/app/komiteer/components/CommiteePage.tsx
apps/web/src/app/komiteer/components/GroupPage.tsx
apps/web/src/app/nodekomiteer/[slug]/page.tsx

Fix group members rendering and add sorting

---

apps/web/src/components/molecules/CompanySplash/CompanySplash.tsx
apps/web/src/components/organisms/EventCalendar/EventCalendarItem.tsx
apps/web/src/components/organisms/EventCalendar/index.tsx

- change config colors for event items in the calendar (yellow/orange for "fadderuka")
- improve mobile view
- dynamic color guide at bottom of calendar

Add event type colors to calendar

---

apps/web/src/app/arrangementer/[slug]/[eventId]/page.tsx
apps/web/src/app/arrangementer/components/EventHeader.tsx

Only shows if you are staff
Also clamps title, but not on mobile

Add dashboard button to event

---

apps/web/src/components/Navbar/MobileNavigation.tsx
apps/web/src/components/Navbar/Navbar.tsx

Update mobile nav

---

apps/rpc/src/bin/server.ts
apps/rpc/src/configuration.ts
apps/rpc/vitest-integration.setup.ts

It hasn't been used for a while now.

Remove ADMIN_USERS environment variable

---

apps/web/src/app/artikler/[slug]/[id]/page.tsx
packages/ui/src/molecules/RichText/RichText.tsx

Fix richtext in darkmode

---

apps/dashboard/src/app/user/page.tsx
apps/dashboard/src/app/user/queries.ts
apps/web/src/app/arrangementer/components/queries.ts
apps/web/src/app/artikler/ArticleList.tsx
apps/web/src/app/artikler/queries.ts

Fix dashboard user list rerendering

---

apps/splash-2025/package.json
apps/splash-2025/src/components/LinjeforeningInfo.tsx
apps/splash-2025/src/components/events.tsx
pnpm-lock.yaml

Hide past events in Splash

---

apps/web/src/app/arrangementer/components/EventDescription.tsx
packages/ui/src/molecules/RichText/RichText.tsx

This fixes a regression removing "read more" on mobile view for event descriptions

Add "read more" to rich text

---

apps/rpc/src/modules/task/task-executor.ts

Let me know if you want me to explain what this does in practice

Execute tasks within a OpenTelemetry span

---

apps/dashboard/src/app/ApplicationShell.tsx

Add plakatbestilling link

---

apps/dashboard/src/app/(internal)/event/components/all-attendees-table.tsx
apps/dashboard/src/app/(internal)/event/mutations.ts
apps/rpc/src/modules/event/attendance-router.ts

Add buttons to move attendees on and off waitlist

---

apps/dashboard/src/app/(internal)/event/[id]/feedback-page.tsx
apps/dashboard/src/app/(internal)/event/components/feedback-form-edit-form.tsx
apps/dashboard/src/app/(internal)/event/mutations.ts
apps/rpc/src/modules/event/event-repository.ts
apps/rpc/src/modules/event/feedback-router.ts
apps/rpc/src/modules/feedback-form/feedback-form-service.ts
packages/types/src/event.ts

Add copy feedback form option

---

apps/rpc/src/modules/event/attendance-service.ts
apps/rpc/src/modules/payment/payment-service.ts

Jo should probably not be bombarded by Stripe

Forward user email to payment creation

---

apps/rpc/src/modules/event/attendance-repository.ts
apps/rpc/src/modules/event/attendance-service.ts
apps/rpc/src/modules/event/event-router.ts
apps/web/src/app/arrangementer/[slug]/[eventId]/page.tsx
apps/web/src/app/arrangementer/components/AttendanceCard/AttendanceCard.tsx
apps/web/src/app/arrangementer/components/AttendanceCard/RegistrationButton.tsx
packages/db/src/fixtures/attendance-pool.ts
packages/db/src/fixtures/attendance.ts
packages/db/src/fixtures/event.ts

This also fixes the backend checks. Oops

Add frontend check for attendee registration in child events

---

packages/config/tailwind.css
packages/ui/src/atoms/Stripes/Stripes.tsx
packages/ui/src/index.ts

this is super unnecessary but it looks kinda cool and we can use it for like the registration button and such to make it super pop
```tsx
<Stripes
colorA="bg-amber-100"
colorB="bg-amber-200"
animated
className="h-24 w-full rounded-lg flex flex-col items-center justify-center"
>
<Text>Superknapp</Text>
</Stripes>
```

Add `<Stripes>` component

---

apps/dashboard/src/app/(internal)/event/components/event-filters.tsx
apps/dashboard/src/app/(internal)/event/page.tsx

Adds a delete search button, prevents submission (so enter doesn't clear the text), and moves skeleton to just table

Improve event searching UX

---

apps/rpc/src/modules/event/attendance-service.ts
apps/rpc/src/modules/event/attendance.e2e-spec.ts

Allow deregistering from an event past deadline when unreserved

---

apps/web/src/app/page.tsx

Add temporary immball popup

---

apps/dashboard/src/app/(internal)/event/[id]/page.tsx

Add link to web from event dashboard page

---

apps/rpc/src/modules/event/attendance-service.ts
apps/rpc/src/modules/task/task-definition.ts
apps/rpc/src/modules/task/task-discovery-service.ts
apps/rpc/src/modules/task/task-executor.ts
apps/rpc/src/modules/task/task-repository.ts
apps/rpc/src/modules/task/task-scheduling-service.ts
packages/db/prisma/migrations/20250908141139_delete_charge_all_attendees_at_once/migration.sql
packages/db/prisma/migrations/20250908141442_payment_charge_deadline/migration.sql
packages/db/prisma/schema.prisma
packages/types/src/attendance.ts

Abides by the 7 day rule imposed by Visa/MasterCard, so that we don't have payments cancelled because they werent charged quickly enough.
This means that each attendee gets MIN(5d, deregisterDeadline) to deregister without having to go through the organizing committee.

Create individual charge tasks for each attendee

---

apps/web/src/components/Navbar/ProfileMenu.tsx

Move feedback form ping to correct link when profile menu is open

---

apps/rpc/src/modules/event/event-router.ts
apps/web/src/app/arrangementer/[slug]/[eventId]/page.tsx
apps/web/src/app/arrangementer/components/EventHeader.tsx

Currently it shows to all staff. It's the little button behind the title

Only show dashboard button to organizers

---

.github/actions/internal/doppler-secrets/action.yml

We can simply disable the entire OTEL SDK

Stop excluding OTEL variables

---

apps/dashboard/src/app/(internal)/company/register/page.tsx

Can't reproduce locally but guessing it's a race condition with the navigate in the mutation

Dont close page when creating company

---

apps/web/src/app/arrangementer/components/AttendanceCard/MainPoolCard.tsx
apps/web/src/app/profil/[profileSlug]/page.tsx
apps/web/src/components/Navbar/ProfileMenu.tsx
packages/db/prisma/schema.prisma

Prefetching the authorize URL will cause cookies to be set, causing OAuth2 state mismatches occasionally when logging in.

Do not prefetch authorize URLs

---

apps/dashboard/src/app/(internal)/job-listing/write-form.tsx

Bedkom finds it pretty annoying to always change the year when adding a joblisting

Change default joblisting dates to today

---

apps/rpc/src/configuration.ts
apps/rpc/src/modules/core.ts
apps/rpc/src/modules/email/email-service.ts
apps/rpc/src/modules/workspace-sync/workspace-service.ts

Cuts down on unnecessary if-statements checking for variables by using some neat typescript type guard inference

Create type guards for configuration options and group workspace and tasks

---

apps/dashboard/src/app/(internal)/punishment/mutations/use-create-mark-mutations.ts
apps/dashboard/src/app/(internal)/punishment/page.tsx
apps/dashboard/src/app/(internal)/punishment/punishment-table.tsx
apps/dashboard/src/app/(internal)/punishment/queries/use-punishment-all-query.ts
apps/dashboard/src/app/(internal)/user/[id]/user-punishment-page.tsx
apps/dashboard/src/app/(internal)/user/queries.ts
apps/rpc/src/modules/mark/mark-repository.ts
apps/rpc/src/modules/mark/mark-router.ts
apps/rpc/src/modules/mark/mark-service.ts

Replaces mark#getAll with mark#findMany and adds infinite scroll to mark table, mutation redirect and orders marks

Add infinite scroll to mark table

---

apps/rpc/src/bin/server.ts
apps/rpc/src/configuration.ts

1. It should not have a default, and 2. it should not just be named HOST

Rename HOST environment variable

---

apps/rpc/src/modules/user/user-router.ts

The requests here are always anonymous

Do not audit user.register

---

apps/web/src/app/bedrifter/CompanyView.tsx

Make company info text readable in dark mode
